// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdumgjdrhptzmphcctyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdW1namRyaHB0em1waGNjdHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTA3ODYsImV4cCI6MjA3NDAyNjc4Nn0.Pl81VZxo8BIs-1AZOoFWkcHnuNDvrBFTWLgkAfZcijs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});